project_id = "ghwyhwcmhemeeixwbfgp"

[functions.moderate-content]
verify_jwt = false

[functions.mux-webhook]
verify_jwt = false

[functions.send-order-access-code]
verify_jwt = false

[functions.verify-order-access-code]
verify_jwt = false

[functions.get-orders-by-email]
verify_jwt = false

[functions.update-attendee-public]
verify_jwt = false

[functions.mark-message-read]
verify_jwt = false

[functions.get-attendee-bookmarks]
verify_jwt = false

[functions.toggle-attendee-bookmark]
verify_jwt = false

[functions.get-system-health]
verify_jwt = false

[functions.get-attendee-conversations]
verify_jwt = false

[functions.get-conversation-messages]
verify_jwt = false

[functions.send-attendee-message]
verify_jwt = false

[functions.create-dm-conversation]
verify_jwt = false

[functions.create-group-conversation]
verify_jwt = false

[functions.join-event-chat]
verify_jwt = false

[functions.get-networkable-attendees]
verify_jwt = false

[functions.update-attendee-profile]
verify_jwt = false

[functions.get-attendee-profile]
verify_jwt = false

[functions.join-session-chat]
verify_jwt = false

[functions.get-message-reactors]
verify_jwt = false

[functions.toggle-message-reaction]
verify_jwt = false